### ISSUE TITLE
RuntimeError: expand(torch.FloatTensor{[3, 256, 256]}, size=[256, 256]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

### ISSUE THREAD

**Issue by Siziff** [learningyan/BeautyREC#4]
RuntimeError: expand(torch.FloatTensor{[3, 256, 256]}, size=[256, 256]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
An error occurs on the test during standard startup, how can I fix it?

**Comment by LonglongaaaGo** [comment]
Hi @Siziff ,
Can I ask how did you solve this problem?
Thank you so much!

**Comment by Siziff** [comment]
Hi @learningyan  I didn't find a solution, I just decided to use another project. If someone answers my question, I will be glad :)

**Comment by MrPetrichor** [comment]
I have solved all the problems and get the right picture. There are few bugs:
1. The model need four inputs:  ori_img, makeup_img, ori_img's parsing,makeup_img's parsing. Well you can get the parsing in /faceutils/mask/main.py， after you get the right parsing, dimension bug will be solved
2. The fucking idiot point is, run /faceutils/mask/main.py can not get the right parsing map!!! The value of the mask is wrong, in /makeuploader/dataset.py ,9 13 are lips, but /faceutils/mask/main.py regard 7 9 are lips!!!! So here is my suggestion: The original map is # mapper = [0, 1, 2, 3, 4, 5, 0, 11, 12, 0, 6, 8, 7, 9, 13, 0, 0, 10, 0] # lip_class   = [7,9]# face_class  = [1,6]  # eyes_class = [4,5], you can change it as mapper = [0, 4, 2, 3, 1, 6, 0, 11, 12, 0, 8, 0, 13, 9, 10, 0, 0, 0, 0] .Then you can get the right mask.

**Comment by MrPetrichor** [comment]
The gt parsing in mtdataset is like this:
![0d384dbbcc121ca5049c423f81c26e6a](https://github.com/learningyan/BeautyREC/assets/59128712/574b5248-843d-47e9-be39-1cfa886765fd)
![show_ori](https://github.com/learningyan/BeautyREC/assets/59128712/1240ef3c-da1b-4606-a8e3-53fca712e5a0)

and if you dont change the mapper you will get:
![show_pre](https://github.com/learningyan/BeautyREC/assets/59128712/073b7e90-364b-4488-b4a0-a90beb649b1e)
which is absolutely wrong, and if you change the mapper as i suggest you can get:
![show_pre1](https://github.com/learningyan/BeautyREC/assets/59128712/697431bf-9511-4481-9f18-989c16d5ac24)
